workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      node: 18
      java: 17

    scripts:
      - npm install --legacy-peer-deps
      - rm -rf ~/.gradle
      - chmod +x node_modules/.bin/cap
      - npx cap sync android
      - chmod +x android/gradlew
      - cd android && ./gradlew --no-daemon clean assembleRelease

    artifacts:
      - android/app/build/outputs/*/.apk
